version: "3.0"
services:
  kb:
    image: ruby:3.2.3-bullseye
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment: 
      - KB_API_URL_TEMPLATE=$KB_API_URL_TEMPLATE
      - KB_PARTNER_KEY=$KB_PARTNER_KEY
      - KB_API_KEY=$KB_API_KEY

volumes:
  bundle:
