name: Publish Gem

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Github whoami
        run: |
          git config user.name 'Barkibot'
          git config user.email 'dev+bot@barkibu.com'
      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
